CREATE TABLE `trade_journal` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` text NOT NULL,
	`trade_event_type` text NOT NULL,
	`request_id` text,
	`client_order_id` text,
	`order_id` text,
	`symbol` text,
	`strategy_name` text,
	`signal_action` text,
	`signal_reason` text,
	`risk_allowed` integer,
	`risk_reasons` text,
	`side` text,
	`quantity` real,
	`limit_price` real,
	`notional` real,
	`latency_ms` real,
	`broker_status` text,
	`mode` text,
	`submitted` integer,
	`filled_qty` real,
	`filled_price` real,
	`realized_pnl` real,
	`hold_days` real,
	`exit_reason` text,
	`error_class` text,
	`error_message` text
);
